apiVersion: v1
kind: Secret
metadata:
  name: {{ include "profile-service.fullname" . }}-secret
  labels:
    {{- include "profile-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secret.databaseUrl | quote }}